name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - compile

jobs:
  build:
    runs-on: ubuntu-latest
    env:  # Define shared environment variables for the entire job
      DASH_ENTERPRISE_HOST: ${{ secrets.DE_HOST }}
      DASH_ENTERPRISE_USERNAME: ${{ secrets.DE_USERNAME }}
      DASH_ENTERPRISE_PASSWORD: ${{ secrets.DE_PASSWORD }}
      APP_NAME: ${{ secrets.DE_APP_NAME }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install de-client
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install de-client --extra-index-url=https://$DASH_ENTERPRISE_HOST/packages

    - name: Create app if it does not exist
      shell: bash
      run: |
        # Create the app if it does not already exist
        exists=$(de --no-keyfile apps exists -n "$APP_NAME")
        if [[ "$exists" == *"App [$APP_NAME] does not exist on [$DASH_ENTERPRISE_HOST]."* ]]; then
          de --no-keyfile apps create -n "$APP_NAME"
        fi

    - name: Inject code and deploy
      shell: bash
      run: |
        de --no-keyfile deploy . --name "$APP_NAME" --message "Deployed commit: $GITHUB_SHA" -y
        de --no-keyfile apps update --name "$APP_NAME"
