name: Triggered Build

on:
  repository_dispatch:
    types:
      - compile

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile and upload artifacts
        run: |
          echo "Compiling stuff..."
          # Your compilation and artifact upload commands go here
